In [42]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (5.0.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (1.20.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)

In [43]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [44]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [45]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

Define the objective function

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [47]:
def objective(trial):
  # Suggest values for the hyperparameters
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  # Create the RandomForestClassifier with the suggested hyperparameters
  clf = RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth = max_depth,
      random_state=42
  )

  # Perform 3-fold cross validation and calculate the accuracy
  scores = cross_val_score(
      clf,
      X_train,
      y_train,
      cv = 3,
      scoring = 'accuracy'
  ).mean()

  # Return the score
  return scores

Create study

In [48]:
study = optuna.create_study(
    direction = 'maximize',
    study_name = 'RandomForestClassifier',
    sampler = optuna.samplers.TPESampler()
)

[I 2026-10-22 05:21:04,563] A new study created in memory with name: RandomForestClassifier

Optimize the study

In [49]:
study.optimize(objective, n_trials = 50)

[I 2026-10-22 05:21:07,369] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 5}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-10-22 05:21:08,925] Trial 1 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 5}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-10-22 05:21:12,766] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 19}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-10-22 05:21:16,196] Trial 3 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 8}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-10-22 05:21:23,211] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 166, 'max_depth': 14}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:28,663] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 156, 'max_depth': 11}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:34,289] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 16}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:37,743] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 110, 'max_depth': 5}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:40,383] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 106, 'max_depth': 5}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:44,455] Trial 9 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 179, 'max_depth': 9}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:45,910] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 60, 'max_depth': 14}. Best is trial 4 with value: 0.7728119180633147.
[I 2026-10-22 05:21:49,117] Trial 11 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 193, 'max_depth': 18}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:21:50,618] Trial 12 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 195, 'max_depth': 18}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:21:52,654] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 200, 'max_depth': 17}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:21:54,820] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 179, 'max_depth': 20}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:21:57,850] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:22:00,828] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 124, 'max_depth': 13}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:22:03,227] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 17}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:22:05,537] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 182, 'max_depth': 18}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:22:07,981] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 197, 'max_depth': 10}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:22:10,313] Trial 20 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 190, 'max_depth': 12}. Best is trial 11 with value: 0.7746741154562384.
[I 2026-10-22 05:22:13,823] Trial 21 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 199, 'max_depth': 19}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-10-22 05:22:16,828] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-10-22 05:22:18,929] Trial 23 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 182, 'max_depth': 16}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-10-22 05:22:21,602] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 178, 'max_depth': 15}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-10-22 05:22:23,448] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 20}. Best is trial 21 with value: 0.7765363128491621.
[I 2026-10-22 05:22:24,637] Trial 26 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 112, 'max_depth': 16}. Best is trial 26 with value: 0.7783985102420856.
[I 2026-10-22 05:22:26,107] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 26 with value: 0.7783985102420856.
[I 2026-10-22 05:22:26,963] Trial 28 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 52, 'max_depth': 10}. Best is trial 26 with value: 0.7783985102420856.
[I 2026-10-22 05:22:28,944] Trial 29 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 127, 'max_depth': 17}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:29,803] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 107, 'max_depth': 17}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:30,605] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 92, 'max_depth': 19}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:30,964] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 53, 'max_depth': 20}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:32,790] Trial 33 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 176, 'max_depth': 3}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:34,284] Trial 34 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 15}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:35,264] Trial 35 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:35,833] Trial 36 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 84, 'max_depth': 11}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:36,320] Trial 37 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 74, 'max_depth': 17}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:37,597] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 20}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:38,486] Trial 39 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 98, 'max_depth': 15}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:40,050] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 155, 'max_depth': 15}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:42,782] Trial 41 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:44,231] Trial 42 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 120, 'max_depth': 15}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:45,776] Trial 43 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 16}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:47,016] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 108, 'max_depth': 13}. Best is trial 29 with value: 0.7783985102420857.
[I 2026-10-22 05:22:48,671] Trial 45 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 16}. Best is trial 45 with value: 0.7802607076350093.
[I 2026-10-22 05:22:50,282] Trial 46 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 139, 'max_depth': 14}. Best is trial 45 with value: 0.7802607076350093.
[I 2026-10-22 05:22:50,902] Trial 47 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 45 with value: 0.7802607076350093.
[I 2026-10-22 05:22:52,603] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 147, 'max_depth': 18}. Best is trial 45 with value: 0.7802607076350093.
[I 2026-10-22 05:22:55,709] Trial 49 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 15}. Best is trial 45 with value: 0.7802607076350093.

Inspect the study

In [50]:
print(f"Best trial: {study.best_trial}")
print(f"Best trial value: {study.best_trial.value}")
print(f"Best trial params: {study.best_trial.params}")

Best trial: FrozenTrial(number=45, state=<TrialState.COMPLETE: 1>, values=[0.7802607076350093], datetime_start=datetime.datetime(2026, 10, 22, 5, 22, 47, 20368), datetime_complete=datetime.datetime(2026, 10, 22, 5, 22, 48, 671470), params={'n_estimators': 129, 'max_depth': 16}, user_attrs={}, system_attrs={'tpe:relative_params:0': '{"max_depth": 16, "n_estimators": 129}'}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=200, log=False, low=50, step=1), 'max_depth': IntDistribution(high=20, log=False, low=3, step=1)}, trial_id=45, value=None)
Best trial value: 0.7802607076350093
Best trial params: {'n_estimators': 129, 'max_depth': 16}

In [51]:
print(f"Best value: {study.best_value}")
print(f"Best params: {study.best_params}")

Best value: 0.7802607076350093
Best params: {'n_estimators': 129, 'max_depth': 16}

Train the model with suggested hyperparameters

In [52]:
best_model = RandomForestClassifier(
    **study.best_trial.params,
    random_state = 42
)

In [53]:
best_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=16, n_estimators=129, random_state=42)

In [54]:
yhat = best_model.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, yhat)

0.7445887445887446

Visualization

In [72]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [57]:
plot_optimization_history(study).show()

In [58]:
plot_parallel_coordinate(study).show()

In [59]:
plot_param_importances(study).show()

In [60]:
plot_contour(study, params=['n_estimators', 'max_depth']).show()

In [61]:
plot_slice(study, params=['n_estimators', 'max_depth']).show()

Samplers in Optuna - RandomizesSearchCV

In [63]:
def objective(trial):
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  clf = RandomForestClassifier(
      n_estimators = n_estimators,
      max_depth = max_depth,
      random_state = 42
  )

  scores = cross_val_score(
      clf,
      X_train,
      y_train,
      cv = 3,
      scoring = 'accuracy'
  ).mean()

  return scores

Create study

In [64]:
study = optuna.create_study(
    direction = 'maximize',
    study_name = "RandomForestClassifier - RandomizedSearchCV",
    sampler = optuna.samplers.RandomSampler()
)
study.optimize(objective, n_trials = 50)

[I 2026-10-22 05:23:48,883] A new study created in memory with name: RandomForestClassifier - RandomizedSearchCV
[I 2026-10-22 05:23:50,672] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 97, 'max_depth': 15}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:23:51,974] Trial 1 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 135, 'max_depth': 3}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:23:52,609] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 63, 'max_depth': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:23:54,641] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 149, 'max_depth': 6}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:23:57,270] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 199, 'max_depth': 7}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:23:58,430] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 101, 'max_depth': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:24:00,413] Trial 6 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 185, 'max_depth': 7}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:24:03,818] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 155, 'max_depth': 11}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:24:05,032] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 84, 'max_depth': 8}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-10-22 05:24:05,843] Trial 9 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:07,338] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 139, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:08,759] Trial 11 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 118, 'max_depth': 11}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:09,376] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 53, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:10,915] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:11,517] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 55, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:12,413] Trial 15 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 5}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:14,040] Trial 16 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 166, 'max_depth': 3}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:17,266] Trial 17 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 170, 'max_depth': 8}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:19,060] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 11}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:20,596] Trial 19 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:21,447] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 73, 'max_depth': 7}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:23,101] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 12}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:24,818] Trial 22 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 164, 'max_depth': 13}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:26,068] Trial 23 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 96, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:27,149] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 94, 'max_depth': 11}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:28,142] Trial 25 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 86, 'max_depth': 6}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:31,638] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 180, 'max_depth': 18}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:32,296] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 52, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:34,256] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 199, 'max_depth': 5}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:34,810] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 55, 'max_depth': 5}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:35,583] Trial 30 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 70, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:37,635] Trial 31 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 194, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:39,243] Trial 32 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 164, 'max_depth': 4}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:39,897] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 64, 'max_depth': 7}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:41,565] Trial 34 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 153, 'max_depth': 3}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:44,633] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 148, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:46,072] Trial 36 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 133, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:47,256] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 114, 'max_depth': 13}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:49,383] Trial 38 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 192, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:50,660] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 84, 'max_depth': 12}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:52,681] Trial 40 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 199, 'max_depth': 3}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:54,418] Trial 41 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 151, 'max_depth': 11}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:57,218] Trial 42 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 180, 'max_depth': 3}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:58,416] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:24:59,329] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 5}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:25:00,523] Trial 45 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 111, 'max_depth': 4}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:25:01,721] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 113, 'max_depth': 13}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:25:03,768] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 145, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:25:05,862] Trial 48 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 182, 'max_depth': 9}. Best is trial 9 with value: 0.7783985102420857.
[I 2026-10-22 05:25:07,721] Trial 49 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 177, 'max_depth': 7}. Best is trial 9 with value: 0.7783985102420857.

Inspect Study

In [65]:
print(f"Best trial: {study.best_trial}")
print(f"Best trial value: {study.best_trial.value}")
print(f"Best trial params: {study.best_trial.params}")
print("-"*45)
print(f"Best value: {study.best_value}")
print(f"Best params: {study.best_params}")

Best trial: FrozenTrial(number=9, state=<TrialState.COMPLETE: 1>, values=[0.7783985102420857], datetime_start=datetime.datetime(2026, 10, 22, 5, 24, 5, 33419), datetime_complete=datetime.datetime(2026, 10, 22, 5, 24, 5, 843852), params={'n_estimators': 75, 'max_depth': 17}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'n_estimators': IntDistribution(high=200, log=False, low=50, step=1), 'max_depth': IntDistribution(high=20, log=False, low=3, step=1)}, trial_id=9, value=None)
Best trial value: 0.7783985102420857
Best trial params: {'n_estimators': 75, 'max_depth': 17}
---------------------------------------------
Best value: 0.7783985102420857
Best params: {'n_estimators': 75, 'max_depth': 17}

Best Model

In [66]:
best_model = RandomForestClassifier(
    **study.best_trial.params,
    random_state = 42
)

best_model.fit(X_train, y_train)
yhat = best_model.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, yhat)}")

Accuracy: 0.7619047619047619

> RandomSampler Outperforms TPESampler

In [67]:
plot_optimization_history(study).show()

In [68]:
plot_parallel_coordinate(study).show()

In [69]:
plot_param_importances(study).show()

In [70]:
plot_contour(study, params=['n_estimators', 'max_depth']).show()

In [74]:
plot_slice(study, params=['n_estimators', 'max_depth']).show()

Optimizing Multiple ML Models

In [75]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [84]:
def objective(trial):
  classifier_name = trial.suggest_categorical('classifier', ['RandomForest', 'GradientBoosting', 'SVM'])

  if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

  elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

  elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

  # Perform cross-validation and return the mean accuracy
  score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
  return score

In [80]:
!pip install cmaes

Collecting cmaes
  Downloading cmaes-0.13.1-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from cmaes) (2.1.3)
Downloading cmaes-0.13.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 4.2 MB/s eta 0:00:00
Installing collected packages: cmaes
Successfully installed cmaes-0.13.1

In [85]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(
    direction='maximize',
    study_name = 'Optimizing Multiple ML Models',
    sampler = optuna.samplers.CmaEsSampler()
)
study.optimize(objective, n_trials=100)

[I 2026-10-22 05:39:31,380] A new study created in memory with name: Optimizing Multiple ML Models
[I 2026-10-22 05:39:31,445] Trial 0 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 1.9679286775148253, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7337057728119181.
[W 2026-10-22 05:39:31,450] The parameter `classifier` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:31,452] The parameter `n_estimators` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:31,454] The parameter `learning_rate` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:31,456] The parameter `max_depth` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:31,458] The parameter `min_samples_split` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:31,460] The parameter `min_samples_leaf` in Trial#1 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:34,693] Trial 1 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 222, 'learning_rate': 0.04374030758447976, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.7616387337057727.
[W 2026-10-22 05:39:34,695] The parameter `classifier` in Trial#2 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,697] The parameter `C` in Trial#2 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,699] The parameter `kernel` in Trial#2 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,702] The parameter `gamma` in Trial#2 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:34,746] Trial 2 finished with value: 0.7579143389199255 and parameters: {'classifier': 'SVM', 'C': 5.9848913757510545, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 1 with value: 0.7616387337057727.
[W 2026-10-22 05:39:34,748] The parameter `classifier` in Trial#3 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,750] The parameter `C` in Trial#3 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,752] The parameter `kernel` in Trial#3 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,753] The parameter `gamma` in Trial#3 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:34,790] Trial 3 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 3.3904381544093365, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7616387337057727.
[W 2026-10-22 05:39:34,791] The parameter `classifier` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,795] The parameter `n_estimators` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,796] The parameter `max_depth` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,797] The parameter `min_samples_split` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,800] The parameter `min_samples_leaf` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:34,802] The parameter `bootstrap` in Trial#4 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:35,576] Trial 4 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 127, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 4 with value: 0.7746741154562384.
[W 2026-10-22 05:39:35,578] The parameter `classifier` in Trial#5 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,579] The parameter `C` in Trial#5 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,581] The parameter `kernel` in Trial#5 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,583] The parameter `gamma` in Trial#5 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:35,620] Trial 5 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.12407495779863824, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.7746741154562384.
[W 2026-10-22 05:39:35,621] The parameter `classifier` in Trial#6 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,623] The parameter `n_estimators` in Trial#6 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,626] The parameter `learning_rate` in Trial#6 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,628] The parameter `max_depth` in Trial#6 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,630] The parameter `min_samples_split` in Trial#6 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:35,632] The parameter `min_samples_leaf` in Trial#6 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:37,370] Trial 6 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 294, 'learning_rate': 0.11920787548554276, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 4 with value: 0.7746741154562384.
[W 2026-10-22 05:39:37,371] The parameter `classifier` in Trial#7 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:37,373] The parameter `n_estimators` in Trial#7 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:37,374] The parameter `max_depth` in Trial#7 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:37,376] The parameter `min_samples_split` in Trial#7 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:37,377] The parameter `min_samples_leaf` in Trial#7 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[W 2026-10-22 05:39:37,379] The parameter `bootstrap` in Trial#7 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.
[I 2026-10-22 05:39:38,178] Trial 7 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 137, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 4 with value: 0.7746741154562384.
[W 2026-10-22 05:39:38,179] The parameter `classifier` in Trial#8 is sampled independently using `RandomSampler` instead of `CmaEsSampler`, potentially degrading the optimization performance. This fallback happened because dynamic search space and `CategoricalDistribution` are not supported by `CmaEsSampler`. You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `CmaEsSampler` if this independent sampling is intended behavior.

In [88]:
print(f"Best trial: {study.best_trial}")
print(f"Best trial value: {study.best_trial.value}")
print(f"Best trial params: {study.best_trial.params}")

Best trial: FrozenTrial(number=90, state=<TrialState.COMPLETE: 1>, values=[0.7858472998137803], datetime_start=datetime.datetime(2026, 10, 22, 5, 41, 8, 414660), datetime_complete=datetime.datetime(2026, 10, 22, 5, 41, 8, 462648), params={'classifier': 'SVM', 'C': 0.31719748239582546, 'kernel': 'linear', 'gamma': 'scale'}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'classifier': CategoricalDistribution(choices=('RandomForest', 'GradientBoosting', 'SVM')), 'C': FloatDistribution(high=100.0, log=True, low=0.1, step=None), 'kernel': CategoricalDistribution(choices=('linear', 'rbf', 'poly', 'sigmoid')), 'gamma': CategoricalDistribution(choices=('scale', 'auto'))}, trial_id=90, value=None)
Best trial value: 0.7858472998137803
Best trial params: {'classifier': 'SVM', 'C': 0.31719748239582546, 'kernel': 'linear', 'gamma': 'scale'}

In [89]:
print(f"Best value: {study.best_value}")
print(f"Best params: {study.best_params}")

Best value: 0.7858472998137803
Best params: {'classifier': 'SVM', 'C': 0.31719748239582546, 'kernel': 'linear', 'gamma': 'scale'}

In [91]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,system_attrs_cma:generation,state
0,0,0.733706,2026-10-22 05:39:31.385264,2026-10-22 05:39:31.444930,0 days 00:00:00.059666,1.967929,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.761639,2026-10-22 05:39:31.447287,2026-10-22 05:39:34.693844,0 days 00:00:03.246557,NaN,NaN,GradientBoosting,NaN,NaN,0.043740,8.0,8.0,7.0,222.0,0.0,COMPLETE
2,2,0.757914,2026-10-22 05:39:34.695086,2026-10-22 05:39:34.746711,0 days 00:00:00.051625,5.984891,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.735568,2026-10-22 05:39:34.747965,2026-10-22 05:39:34.790354,0 days 00:00:00.042389,3.390438,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.774674,2026-10-22 05:39:34.791527,2026-10-22 05:39:35.576603,0 days 00:00:00.785076,NaN,False,RandomForest,NaN,NaN,NaN,13.0,2.0,2.0,127.0,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.743017,2026-10-22 05:41:10.521058,2026-10-22 05:41:14.096811,0 days 00:00:03.575753,NaN,NaN,GradientBoosting,NaN,NaN,0.102218,19.0,2.0,2.0,102.0,NaN,COMPLETE
96,96,0.756052,2026-10-22 05:41:14.097956,2026-10-22 05:41:18.349863,0 days 00:00:04.251907,NaN,NaN,GradientBoosting,NaN,NaN,0.010464,20.0,5.0,8.0,178.0,NaN,COMPLETE
97,97,0.731844,2026-10-22 05:41:18.353498,2026-10-22 05:41:19.841755,0 days 00:00:01.488257,NaN,NaN,GradientBoosting,NaN,NaN,0.278529,13.0,10.0,4.0,112.0,NaN,COMPLETE
98,98,0.677840,2026-10-22 05:41:19.843121,2026-10-22 05:41:19.966267,0 days 00:00:00.123146,65.053245,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.703911,2026-10-22 05:41:19.967406,2026-10-22 05:41:20.066913,0 days 00:00:00.099507,39.393235,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [94]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 42
RandomForest        30
GradientBoosting    28
Name: count, dtype: int64

In [95]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.749268
RandomForest        0.766791
SVM                 0.739026
Name: value, dtype: float64

In [103]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score

# 1. Safely copy the winning parameters from your study
best_params = study.best_trial.params.copy()

# 2. Extract and remove the model name so it doesn't break scikit-learn
winning_classifier = best_params.pop('classifier')

print(f"🏆 The winning model selected by Optuna is: {winning_classifier}")

# 3. Dynamically initialize the correct winning model architecture
if winning_classifier == 'SVM':
    best_model = SVC(**best_params, random_state=42)

elif winning_classifier == 'RandomForest':
    best_model = RandomForestClassifier(**best_params, random_state=42)

elif winning_classifier == 'GradientBoosting':
    best_model = GradientBoostingClassifier(**best_params, random_state=42)

# 4. Train the winning model on your complete training set
best_model.fit(X_train, y_train)

# 5. Generate final predictions and print the evaluation score
yhat = best_model.predict(X_test)
final_accuracy = accuracy_score(y_test, yhat)

print(f"🎯 Final Unbiased Test Accuracy: {final_accuracy:.4f}")

🏆 The winning model selected by Optuna is: SVM
🎯 Final Unbiased Test Accuracy: 0.7446

Iris Dataset

In [105]:
! pip install optuna-integration[xgboost]

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-5.0.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (5.0.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (3.4.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (1.20.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.1.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (2.32.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.16.0)
Downloading optuna_integration-5.0.0-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 3.1 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-5.0.0

In [107]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print('-'*56)
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-10-22 06:05:07,145] A new study created in memory with name: no-name-6c858490-095a-460e-b417-351a91f540d6

[0]	train-mlogloss:0.88773	eval-mlogloss:0.87815
[1]	train-mlogloss:0.72586	eval-mlogloss:0.70944
[2]	train-mlogloss:0.67656	eval-mlogloss:0.66932
[3]	train-mlogloss:0.63661	eval-mlogloss:0.63109
[4]	train-mlogloss:0.54000	eval-mlogloss:0.52649
[5]	train-mlogloss:0.45357	eval-mlogloss:0.42582
[6]	train-mlogloss:0.43676	eval-mlogloss:0.41082
[7]	train-mlogloss:0.41155	eval-mlogloss:0.38059
[8]	train-mlogloss:0.38135	eval-mlogloss:0.34673
[9]	train-mlogloss:0.35049	eval-mlogloss:0.30833
[10]	train-mlogloss:0.33974	eval-mlogloss:0.29325
[11]	train-mlogloss:0.31312	eval-mlogloss:0.26006
[12]	train-mlogloss:0.28631	eval-mlogloss:0.23053
[13]	train-mlogloss:0.27606	eval-mlogloss:0.21926
[14]	train-mlogloss:0.27487	eval-mlogloss:0.21884
[15]	train-mlogloss:0.27363	eval-mlogloss:0.21799
[16]	train-mlogloss:0.26173	eval-mlogloss:0.20352
[17]	train-mlogloss:0.26074	eval-mlogloss:0.20298
[18]	train-mlogloss:0.26074	eval-mlogloss:0.20298
[19]	train-mlogloss:0.26079	eval-mlogloss:0.20276
[20]	train-mlogloss:0.26080	eval-mlogloss:0.20273
[21]	train-mlogloss:0.26079	eval-mlogloss:0.20274
[22]	train-mlogloss:0.26076	eval-mlogloss:0.20282
[23]	train-mlogloss:0.26076	eval-mlogloss:0.20282
[24]	train-mlogloss:0.26066	eval-mlogloss:0.20317
[25]	train-mlogloss:0.26072	eval-mlogloss:0.20300
[26]	train-mlogloss:0.26072	eval-mlogloss:0.20300
[27]	train-mlogloss:0.26066	eval-mlogloss:0.20328
[28]	train-mlogloss:0.26004	eval-mlogloss:0.20371
[29]	train-mlogloss:0.25984	eval-mlogloss:0.20330
[30]	train-mlogloss:0.25979	eval-mlogloss:0.20344
[31]	train-mlogloss:0.25911	eval-mlogloss:0.20306
[32]	train-mlogloss:0.25909	eval-mlogloss:0.20321
[33]	train-mlogloss:0.25922	eval-mlogloss:0.20312
[34]	train-mlogloss:0.25921	eval-mlogloss:0.20312
[35]	train-mlogloss:0.25921	eval-mlogloss:0.20312
[36]	train-mlogloss:0.25918	eval-mlogloss:0.20288
[37]	train-mlogloss:0.25918	eval-mlogloss:0.20288
[38]	train-mlogloss:0.25920	eval-mlogloss:0.20282
[39]	train-mlogloss:0.25832	eval-mlogloss:0.20267
[40]	train-mlogloss:0.25216	eval-mlogloss:0.19497
[41]	train-mlogloss:0.25214	eval-mlogloss:0.19518
[42]	train-mlogloss:0.25218	eval-mlogloss:0.19524
[43]	train-mlogloss:0.25218	eval-mlogloss:0.19525
[44]	train-mlogloss:0.25218	eval-mlogloss:0.19525
[45]	train-mlogloss:0.25220	eval-mlogloss:0.19558
[46]	train-mlogloss:0.25218	eval-mlogloss:0.19557
[47]	train-mlogloss:0.25218	eval-mlogloss:0.19557
[48]	train-mlogloss:0.25193	eval-mlogloss:0.19414
[49]	train-mlogloss:0.25115	eval-mlogloss:0.19319
[50]	train-mlogloss:0.24667	eval-mlogloss:0.18707
[51]	train-mlogloss:0.24667	eval-mlogloss:0.18707
[52]	train-mlogloss:0.24641	eval-mlogloss:0.18696
[53]	train-mlogloss:0.24641	eval-mlogloss:0.18700
[54]	train-mlogloss:0.24641	eval-mlogloss:0.18686
[55]	train-mlogloss:0.24611	eval-mlogloss:0.18584
[56]	train-mlogloss:0.24611	eval-mlogloss:0.18584
[57]	train-mlogloss:0.24611	eval-mlogloss:0.18584
[58]	train-mlogloss:0.24559	eval-mlogloss:0.18568
[59]	train-mlogloss:0.24560	eval-mlogloss:0.18574
[60]	train-mlogloss:0.24560	eval-mlogloss:0.18574
[61]	train-mlogloss:0.24560	eval-mlogloss:0.18585
[62]	train-mlogloss:0.24555	eval-mlogloss:0.18613
[63]	train-mlogloss:0.24554	eval-mlogloss:0.18614
[64]	train-mlogloss:0.24554	eval-mlogloss:0.18614
[65]	train-mlogloss:0.24553	eval-mlogloss:0.18600
[66]	train-mlogloss:0.24554	eval-mlogloss:0.18512
[67]	train-mlogloss:0.24554	eval-mlogloss:0.18512
[68]	train-mlogloss:0.24553	eval-mlogloss:0.18530
[69]	train-mlogloss:0.24553	eval-mlogloss:0.18530
[70]	train-mlogloss:0.24553	eval-mlogloss:0.18530
[71]	train-mlogloss:0.24551	eval-mlogloss:0.18542
[72]	train-mlogloss:0.24550	eval-mlogloss:0.18541
[73]	train-mlogloss:0.24550	eval-mlogloss:0.18541
[74]	train-mlogloss:0.24546	eval-mlogloss:0.18554
[75]	train-mlogloss:0.24543	eval-mlogloss:0.18537
[76]	train-mlogloss:0.24542	eval-mlogloss:0.18538
[77]	train-mlogloss:0.24547	eval-mlogloss:0.18502
[78]	train-mlogloss:0.24548	eval-mlogloss:0.18505
[79]	train-mlogloss:0.24512	eval-mlogloss:0.18490
[80]	train-mlogloss:0.24509	eval-mlogloss:0.18511
[81]	train-mlogloss:0.24509	eval-mlogloss:0.18511
[82]	train-mlogloss:0.24509	eval-mlogloss:0.18531
[83]	train-mlogloss:0.24414	eval-mlogloss:0.18432
[84]	train-mlogloss:0.24414	eval-mlogloss:0.18432
[85]	train-mlogloss:0.24381	eval-mlogloss:0.18429
[86]	train-mlogloss:0.24381	eval-mlogloss:0.18432
[87]	train-mlogloss:0.24381	eval-mlogloss:0.18473
[88]	train-mlogloss:0.24329	eval-mlogloss:0.18430
[89]	train-mlogloss:0.24329	eval-mlogloss:0.18430
[90]	train-mlogloss:0.24329	eval-mlogloss:0.18430
[91]	train-mlogloss:0.24339	eval-mlogloss:0.18376
[92]	train-mlogloss:0.24338	eval-mlogloss:0.18375
[93]	train-mlogloss:0.24335	eval-mlogloss:0.18367
[94]	train-mlogloss:0.24331	eval-mlogloss:0.18391
[95]	train-mlogloss:0.24330	eval-mlogloss:0.18409
[96]	train-mlogloss:0.24329	eval-mlogloss:0.18420
[97]	train-mlogloss:0.24327	eval-mlogloss:0.18438
[98]	train-mlogloss:0.24327	eval-mlogloss:0.18436
[99]	train-mlogloss:0.24315	eval-mlogloss:0.18473
[100]	train-mlogloss:0.24315	eval-mlogloss:0.18473
[101]	train-mlogloss:0.24315	eval-mlogloss:0.18473
[102]	train-mlogloss:0.24315	eval-mlogloss:0.18473
[103]	train-mlogloss:0.24310	eval-mlogloss:0.18502
[104]	train-mlogloss:0.24256	eval-mlogloss:0.18490
[105]	train-mlogloss:0.24256	eval-mlogloss:0.18490
[106]	train-mlogloss:0.24256	eval-mlogloss:0.18490
[107]	train-mlogloss:0.24257	eval-mlogloss:0.18481
[108]	train-mlogloss:0.24257	eval-mlogloss:0.18481
[109]	train-mlogloss:0.24257	eval-mlogloss:0.18481
[110]	train-mlogloss:0.24257	eval-mlogloss:0.18481
[111]	train-mlogloss:0.24257	eval-mlogloss:0.18519
[112]	train-mlogloss:0.24228	eval-mlogloss:0.18505
[113]	train-mlogloss:0.24228	eval-mlogloss:0.18505
[114]	train-mlogloss:0.24228	eval-mlogloss:0.18505
[115]	train-mlogloss:0.24228	eval-mlogloss:0.18505
[116]	train-mlogloss:0.24228	eval-mlogloss:0.18501
[117]	train-mlogloss:0.24230	eval-mlogloss:0.18525
[118]	train-mlogloss:0.24236	eval-mlogloss:0.18571
[119]	train-mlogloss:0.24238	eval-mlogloss:0.18582
[120]	train-mlogloss:0.24241	eval-mlogloss:0.18599
[121]	train-mlogloss:0.24242	eval-mlogloss:0.18608
[122]	train-mlogloss:0.24242	eval-mlogloss:0.18608
[123]	train-mlogloss:0.24228	eval-mlogloss:0.18484

[I 2026-10-22 06:05:10,113] Trial 0 finished with value: 1.0 and parameters: {'lambda': 7.03696704899017e-08, 'alpha': 0.8729637882394724, 'eta': 0.2546503079459186, 'gamma': 0.07877455511076698, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.7007462482960004, 'colsample_bytree': 0.4784077962774125}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.79024	eval-mlogloss:0.77050
[1]	train-mlogloss:0.65052	eval-mlogloss:0.62250
[2]	train-mlogloss:0.54343	eval-mlogloss:0.49732
[3]	train-mlogloss:0.48607	eval-mlogloss:0.44170
[4]	train-mlogloss:0.42741	eval-mlogloss:0.39163
[5]	train-mlogloss:0.42392	eval-mlogloss:0.38995
[6]	train-mlogloss:0.41714	eval-mlogloss:0.38322
[7]	train-mlogloss:0.39619	eval-mlogloss:0.35096
[8]	train-mlogloss:0.38046	eval-mlogloss:0.32973
[9]	train-mlogloss:0.37835	eval-mlogloss:0.32841
[10]	train-mlogloss:0.37830	eval-mlogloss:0.32840
[11]	train-mlogloss:0.37500	eval-mlogloss:0.31973
[12]	train-mlogloss:0.37139	eval-mlogloss:0.31888
[13]	train-mlogloss:0.34932	eval-mlogloss:0.29749
[14]	train-mlogloss:0.34839	eval-mlogloss:0.29702
[15]	train-mlogloss:0.34649	eval-mlogloss:0.29627
[16]	train-mlogloss:0.34649	eval-mlogloss:0.29631
[17]	train-mlogloss:0.34651	eval-mlogloss:0.29628
[18]	train-mlogloss:0.34657	eval-mlogloss:0.29628
[19]	train-mlogloss:0.34677	eval-mlogloss:0.29646
[20]	train-mlogloss:0.34590	eval-mlogloss:0.29341
[21]	train-mlogloss:0.34596	eval-mlogloss:0.29342
[22]	train-mlogloss:0.34592	eval-mlogloss:0.29343
[23]	train-mlogloss:0.34673	eval-mlogloss:0.29353
[24]	train-mlogloss:0.34596	eval-mlogloss:0.29341
[25]	train-mlogloss:0.34621	eval-mlogloss:0.29363
[26]	train-mlogloss:0.34524	eval-mlogloss:0.29254
[27]	train-mlogloss:0.34527	eval-mlogloss:0.29245
[28]	train-mlogloss:0.34319	eval-mlogloss:0.29227
[29]	train-mlogloss:0.34335	eval-mlogloss:0.29222
[30]	train-mlogloss:0.34306	eval-mlogloss:0.29210
[31]	train-mlogloss:0.34254	eval-mlogloss:0.28935
[32]	train-mlogloss:0.34236	eval-mlogloss:0.28917
[33]	train-mlogloss:0.34277	eval-mlogloss:0.28903
[34]	train-mlogloss:0.34281	eval-mlogloss:0.28904
[35]	train-mlogloss:0.34290	eval-mlogloss:0.28912
[36]	train-mlogloss:0.34291	eval-mlogloss:0.28904
[37]	train-mlogloss:0.34282	eval-mlogloss:0.28902
[38]	train-mlogloss:0.34292	eval-mlogloss:0.28909
[39]	train-mlogloss:0.34244	eval-mlogloss:0.28906
[40]	train-mlogloss:0.34233	eval-mlogloss:0.28930
[41]	train-mlogloss:0.34225	eval-mlogloss:0.28925
[42]	train-mlogloss:0.34201	eval-mlogloss:0.28934
[43]	train-mlogloss:0.34188	eval-mlogloss:0.28916
[44]	train-mlogloss:0.33955	eval-mlogloss:0.28694
[45]	train-mlogloss:0.33944	eval-mlogloss:0.28701
[46]	train-mlogloss:0.33928	eval-mlogloss:0.28666
[47]	train-mlogloss:0.33946	eval-mlogloss:0.28636
[48]	train-mlogloss:0.33902	eval-mlogloss:0.28407
[49]	train-mlogloss:0.33850	eval-mlogloss:0.28459
[50]	train-mlogloss:0.33563	eval-mlogloss:0.28296
[51]	train-mlogloss:0.33625	eval-mlogloss:0.28381
[52]	train-mlogloss:0.33557	eval-mlogloss:0.28356
[53]	train-mlogloss:0.31176	eval-mlogloss:0.25608
[54]	train-mlogloss:0.31161	eval-mlogloss:0.25546
[55]	train-mlogloss:0.31119	eval-mlogloss:0.25514
[56]	train-mlogloss:0.31117	eval-mlogloss:0.25486
[57]	train-mlogloss:0.31083	eval-mlogloss:0.25509
[58]	train-mlogloss:0.31077	eval-mlogloss:0.25507
[59]	train-mlogloss:0.31094	eval-mlogloss:0.25482
[60]	train-mlogloss:0.30918	eval-mlogloss:0.25483
[61]	train-mlogloss:0.30897	eval-mlogloss:0.25469
[62]	train-mlogloss:0.30890	eval-mlogloss:0.25481
[63]	train-mlogloss:0.30850	eval-mlogloss:0.25267
[64]	train-mlogloss:0.30748	eval-mlogloss:0.25090
[65]	train-mlogloss:0.30760	eval-mlogloss:0.25077
[66]	train-mlogloss:0.30750	eval-mlogloss:0.25088
[67]	train-mlogloss:0.30746	eval-mlogloss:0.25089
[68]	train-mlogloss:0.30760	eval-mlogloss:0.25092
[69]	train-mlogloss:0.30768	eval-mlogloss:0.25120
[70]	train-mlogloss:0.30762	eval-mlogloss:0.25108
[71]	train-mlogloss:0.30810	eval-mlogloss:0.25199
[72]	train-mlogloss:0.30773	eval-mlogloss:0.25151
[73]	train-mlogloss:0.30773	eval-mlogloss:0.25067
[74]	train-mlogloss:0.30794	eval-mlogloss:0.25145
[75]	train-mlogloss:0.30759	eval-mlogloss:0.25080
[76]	train-mlogloss:0.30762	eval-mlogloss:0.25069
[77]	train-mlogloss:0.30820	eval-mlogloss:0.25080
[78]	train-mlogloss:0.30791	eval-mlogloss:0.25069
[79]	train-mlogloss:0.30768	eval-mlogloss:0.25061
[80]	train-mlogloss:0.30753	eval-mlogloss:0.25068
[81]	train-mlogloss:0.30756	eval-mlogloss:0.25066
[82]	train-mlogloss:0.30747	eval-mlogloss:0.25078
[83]	train-mlogloss:0.30745	eval-mlogloss:0.25279
[84]	train-mlogloss:0.30742	eval-mlogloss:0.25302
[85]	train-mlogloss:0.30756	eval-mlogloss:0.25345
[86]	train-mlogloss:0.30743	eval-mlogloss:0.25315
[87]	train-mlogloss:0.30777	eval-mlogloss:0.25382
[88]	train-mlogloss:0.30752	eval-mlogloss:0.25338
[89]	train-mlogloss:0.30765	eval-mlogloss:0.25375
[90]	train-mlogloss:0.30773	eval-mlogloss:0.25332
[91]	train-mlogloss:0.30791	eval-mlogloss:0.25326
[92]	train-mlogloss:0.30821	eval-mlogloss:0.25331
[93]	train-mlogloss:0.30806	eval-mlogloss:0.25256
[94]	train-mlogloss:0.30766	eval-mlogloss:0.25248
[95]	train-mlogloss:0.30758	eval-mlogloss:0.25249
[96]	train-mlogloss:0.30747	eval-mlogloss:0.25255
[97]	train-mlogloss:0.30656	eval-mlogloss:0.25196
[98]	train-mlogloss:0.30681	eval-mlogloss:0.25210
[99]	train-mlogloss:0.30717	eval-mlogloss:0.25171
[100]	train-mlogloss:0.30725	eval-mlogloss:0.25176
[101]	train-mlogloss:0.30708	eval-mlogloss:0.25185
[102]	train-mlogloss:0.30696	eval-mlogloss:0.25192
[103]	train-mlogloss:0.30684	eval-mlogloss:0.25239
[104]	train-mlogloss:0.30686	eval-mlogloss:0.25230
[105]	train-mlogloss:0.30670	eval-mlogloss:0.25207
[106]	train-mlogloss:0.30654	eval-mlogloss:0.25210
[107]	train-mlogloss:0.30655	eval-mlogloss:0.25181
[108]	train-mlogloss:0.30655	eval-mlogloss:0.25184
[109]	train-mlogloss:0.30667	eval-mlogloss:0.25231

[I 2026-10-22 06:05:11,125] Trial 1 finished with value: 0.9666666666666667 and parameters: {'lambda': 0.0003828511283095817, 'alpha': 0.027875052038043288, 'eta': 0.2790926033737542, 'gamma': 0.17316612236046075, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.455025564544148, 'colsample_bytree': 0.9018244894352763}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.86803	eval-mlogloss:0.85589
[1]	train-mlogloss:0.69609	eval-mlogloss:0.67001
[2]	train-mlogloss:0.58006	eval-mlogloss:0.55047
[3]	train-mlogloss:0.48855	eval-mlogloss:0.45439

[I 2026-10-22 06:05:11,178] Trial 2 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.05660	eval-mlogloss:1.05590
[1]	train-mlogloss:1.01666	eval-mlogloss:1.01289
[2]	train-mlogloss:0.97910	eval-mlogloss:0.97369
[3]	train-mlogloss:0.94414	eval-mlogloss:0.93712
[4]	train-mlogloss:0.91047	eval-mlogloss:0.90241
[5]	train-mlogloss:0.87916	eval-mlogloss:0.86970
[6]	train-mlogloss:0.84869	eval-mlogloss:0.83848
[7]	train-mlogloss:0.81999	eval-mlogloss:0.80834
[8]	train-mlogloss:0.79232	eval-mlogloss:0.77858
[9]	train-mlogloss:0.76559	eval-mlogloss:0.75092
[10]	train-mlogloss:0.74028	eval-mlogloss:0.72468
[11]	train-mlogloss:0.71661	eval-mlogloss:0.69952
[12]	train-mlogloss:0.69357	eval-mlogloss:0.67562
[13]	train-mlogloss:0.67136	eval-mlogloss:0.65230
[14]	train-mlogloss:0.65024	eval-mlogloss:0.63057
[15]	train-mlogloss:0.62993	eval-mlogloss:0.60979
[16]	train-mlogloss:0.61120	eval-mlogloss:0.59001
[17]	train-mlogloss:0.59301	eval-mlogloss:0.57054
[18]	train-mlogloss:0.57528	eval-mlogloss:0.55222
[19]	train-mlogloss:0.55897	eval-mlogloss:0.53434
[20]	train-mlogloss:0.54262	eval-mlogloss:0.51712
[21]	train-mlogloss:0.52717	eval-mlogloss:0.50004
[22]	train-mlogloss:0.51251	eval-mlogloss:0.48388
[23]	train-mlogloss:0.49818	eval-mlogloss:0.46888
[24]	train-mlogloss:0.48456	eval-mlogloss:0.45392
[25]	train-mlogloss:0.47099	eval-mlogloss:0.43986
[26]	train-mlogloss:0.45809	eval-mlogloss:0.42618
[27]	train-mlogloss:0.44531	eval-mlogloss:0.41258
[28]	train-mlogloss:0.43347	eval-mlogloss:0.40039
[29]	train-mlogloss:0.42218	eval-mlogloss:0.38854
[30]	train-mlogloss:0.41127	eval-mlogloss:0.37648
[31]	train-mlogloss:0.40057	eval-mlogloss:0.36489
[32]	train-mlogloss:0.39020	eval-mlogloss:0.35373
[33]	train-mlogloss:0.38072	eval-mlogloss:0.34354
[34]	train-mlogloss:0.37119	eval-mlogloss:0.33312
[35]	train-mlogloss:0.36225	eval-mlogloss:0.32321
[36]	train-mlogloss:0.35384	eval-mlogloss:0.31398
[37]	train-mlogloss:0.34602	eval-mlogloss:0.30516
[38]	train-mlogloss:0.33822	eval-mlogloss:0.29636
[39]	train-mlogloss:0.33080	eval-mlogloss:0.28830
[40]	train-mlogloss:0.32391	eval-mlogloss:0.28101
[41]	train-mlogloss:0.31744	eval-mlogloss:0.27414
[42]	train-mlogloss:0.31063	eval-mlogloss:0.26644
[43]	train-mlogloss:0.30439	eval-mlogloss:0.25895
[44]	train-mlogloss:0.29834	eval-mlogloss:0.25201
[45]	train-mlogloss:0.29295	eval-mlogloss:0.24572
[46]	train-mlogloss:0.28755	eval-mlogloss:0.24018
[47]	train-mlogloss:0.28315	eval-mlogloss:0.23528
[48]	train-mlogloss:0.27797	eval-mlogloss:0.22946
[49]	train-mlogloss:0.27377	eval-mlogloss:0.22474
[50]	train-mlogloss:0.26879	eval-mlogloss:0.21904
[51]	train-mlogloss:0.26409	eval-mlogloss:0.21358
[52]	train-mlogloss:0.25961	eval-mlogloss:0.20842
[53]	train-mlogloss:0.25577	eval-mlogloss:0.20423
[54]	train-mlogloss:0.25166	eval-mlogloss:0.19937
[55]	train-mlogloss:0.24812	eval-mlogloss:0.19530
[56]	train-mlogloss:0.24496	eval-mlogloss:0.19168
[57]	train-mlogloss:0.24176	eval-mlogloss:0.18828
[58]	train-mlogloss:0.23847	eval-mlogloss:0.18457
[59]	train-mlogloss:0.23527	eval-mlogloss:0.18119
[60]	train-mlogloss:0.23231	eval-mlogloss:0.17751
[61]	train-mlogloss:0.22941	eval-mlogloss:0.17447
[62]	train-mlogloss:0.22659	eval-mlogloss:0.17111
[63]	train-mlogloss:0.22537	eval-mlogloss:0.16967

[I 2026-10-22 06:05:11,682] Trial 3 pruned. Trial was pruned at iteration 64.

[0]	train-mlogloss:1.02662	eval-mlogloss:1.02736

[I 2026-10-22 06:05:11,707] Trial 4 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08710	eval-mlogloss:1.08924
[1]	train-mlogloss:1.07355	eval-mlogloss:1.07495
[2]	train-mlogloss:1.06044	eval-mlogloss:1.06106
[3]	train-mlogloss:1.04862	eval-mlogloss:1.04885
[4]	train-mlogloss:1.03598	eval-mlogloss:1.03563
[5]	train-mlogloss:1.02456	eval-mlogloss:1.02449
[6]	train-mlogloss:1.01316	eval-mlogloss:1.01287
[7]	train-mlogloss:1.00414	eval-mlogloss:1.00420
[8]	train-mlogloss:0.99276	eval-mlogloss:0.99202
[9]	train-mlogloss:0.98100	eval-mlogloss:0.97990
[10]	train-mlogloss:0.96966	eval-mlogloss:0.96776
[11]	train-mlogloss:0.95864	eval-mlogloss:0.95600
[12]	train-mlogloss:0.94915	eval-mlogloss:0.94674
[13]	train-mlogloss:0.93986	eval-mlogloss:0.93748
[14]	train-mlogloss:0.92883	eval-mlogloss:0.92615
[15]	train-mlogloss:0.91825	eval-mlogloss:0.91488
[16]	train-mlogloss:0.90795	eval-mlogloss:0.90385
[17]	train-mlogloss:0.89782	eval-mlogloss:0.89318
[18]	train-mlogloss:0.88783	eval-mlogloss:0.88254
[19]	train-mlogloss:0.87936	eval-mlogloss:0.87420
[20]	train-mlogloss:0.86985	eval-mlogloss:0.86462
[21]	train-mlogloss:0.86021	eval-mlogloss:0.85424
[22]	train-mlogloss:0.85286	eval-mlogloss:0.84630
[23]	train-mlogloss:0.84366	eval-mlogloss:0.83657
[24]	train-mlogloss:0.83466	eval-mlogloss:0.82696
[25]	train-mlogloss:0.82537	eval-mlogloss:0.81734
[26]	train-mlogloss:0.81643	eval-mlogloss:0.80798
[27]	train-mlogloss:0.80736	eval-mlogloss:0.79843
[28]	train-mlogloss:0.79864	eval-mlogloss:0.78924
[29]	train-mlogloss:0.79027	eval-mlogloss:0.78023
[30]	train-mlogloss:0.78329	eval-mlogloss:0.77297
[31]	train-mlogloss:0.77486	eval-mlogloss:0.76431
[32]	train-mlogloss:0.76644	eval-mlogloss:0.75558
[33]	train-mlogloss:0.76088	eval-mlogloss:0.75006
[34]	train-mlogloss:0.75260	eval-mlogloss:0.74137
[35]	train-mlogloss:0.74491	eval-mlogloss:0.73327
[36]	train-mlogloss:0.73707	eval-mlogloss:0.72507
[37]	train-mlogloss:0.73003	eval-mlogloss:0.71769
[38]	train-mlogloss:0.72368	eval-mlogloss:0.71155
[39]	train-mlogloss:0.71605	eval-mlogloss:0.70338
[40]	train-mlogloss:0.70949	eval-mlogloss:0.69675
[41]	train-mlogloss:0.70365	eval-mlogloss:0.69093
[42]	train-mlogloss:0.69761	eval-mlogloss:0.68483
[43]	train-mlogloss:0.69054	eval-mlogloss:0.67709
[44]	train-mlogloss:0.68473	eval-mlogloss:0.67103
[45]	train-mlogloss:0.67791	eval-mlogloss:0.66352
[46]	train-mlogloss:0.67172	eval-mlogloss:0.65690
[47]	train-mlogloss:0.66499	eval-mlogloss:0.64959
[48]	train-mlogloss:0.65848	eval-mlogloss:0.64290
[49]	train-mlogloss:0.65218	eval-mlogloss:0.63622
[50]	train-mlogloss:0.64692	eval-mlogloss:0.63080
[51]	train-mlogloss:0.64047	eval-mlogloss:0.62427
[52]	train-mlogloss:0.63412	eval-mlogloss:0.61761
[53]	train-mlogloss:0.62899	eval-mlogloss:0.61230
[54]	train-mlogloss:0.62302	eval-mlogloss:0.60578
[55]	train-mlogloss:0.61699	eval-mlogloss:0.59931
[56]	train-mlogloss:0.61118	eval-mlogloss:0.59308
[57]	train-mlogloss:0.60671	eval-mlogloss:0.58846
[58]	train-mlogloss:0.60183	eval-mlogloss:0.58363
[59]	train-mlogloss:0.59618	eval-mlogloss:0.57757
[60]	train-mlogloss:0.59084	eval-mlogloss:0.57196
[61]	train-mlogloss:0.58533	eval-mlogloss:0.56605
[62]	train-mlogloss:0.57973	eval-mlogloss:0.55991
[63]	train-mlogloss:0.57439	eval-mlogloss:0.55421
[64]	train-mlogloss:0.56905	eval-mlogloss:0.54878
[65]	train-mlogloss:0.56596	eval-mlogloss:0.54592
[66]	train-mlogloss:0.56067	eval-mlogloss:0.54019
[67]	train-mlogloss:0.55512	eval-mlogloss:0.53423
[68]	train-mlogloss:0.55124	eval-mlogloss:0.53030
[69]	train-mlogloss:0.54619	eval-mlogloss:0.52500
[70]	train-mlogloss:0.54295	eval-mlogloss:0.52192
[71]	train-mlogloss:0.53811	eval-mlogloss:0.51669
[72]	train-mlogloss:0.53312	eval-mlogloss:0.51133
[73]	train-mlogloss:0.52952	eval-mlogloss:0.50802
[74]	train-mlogloss:0.52465	eval-mlogloss:0.50281
[75]	train-mlogloss:0.52212	eval-mlogloss:0.50058
[76]	train-mlogloss:0.51728	eval-mlogloss:0.49548
[77]	train-mlogloss:0.51266	eval-mlogloss:0.49074
[78]	train-mlogloss:0.50812	eval-mlogloss:0.48585
[79]	train-mlogloss:0.50347	eval-mlogloss:0.48102
[80]	train-mlogloss:0.49950	eval-mlogloss:0.47684
[81]	train-mlogloss:0.49587	eval-mlogloss:0.47311
[82]	train-mlogloss:0.49198	eval-mlogloss:0.46904
[83]	train-mlogloss:0.48774	eval-mlogloss:0.46442
[84]	train-mlogloss:0.48345	eval-mlogloss:0.45986
[85]	train-mlogloss:0.47915	eval-mlogloss:0.45523
[86]	train-mlogloss:0.47517	eval-mlogloss:0.45092
[87]	train-mlogloss:0.47106	eval-mlogloss:0.44655
[88]	train-mlogloss:0.46706	eval-mlogloss:0.44214
[89]	train-mlogloss:0.46315	eval-mlogloss:0.43789
[90]	train-mlogloss:0.45915	eval-mlogloss:0.43359
[91]	train-mlogloss:0.45594	eval-mlogloss:0.43018
[92]	train-mlogloss:0.45286	eval-mlogloss:0.42694
[93]	train-mlogloss:0.44911	eval-mlogloss:0.42291
[94]	train-mlogloss:0.44632	eval-mlogloss:0.42009
[95]	train-mlogloss:0.44271	eval-mlogloss:0.41624
[96]	train-mlogloss:0.43983	eval-mlogloss:0.41334
[97]	train-mlogloss:0.43623	eval-mlogloss:0.40941
[98]	train-mlogloss:0.43386	eval-mlogloss:0.40737
[99]	train-mlogloss:0.43028	eval-mlogloss:0.40350
[100]	train-mlogloss:0.42740	eval-mlogloss:0.40045
[101]	train-mlogloss:0.42438	eval-mlogloss:0.39732
[102]	train-mlogloss:0.42090	eval-mlogloss:0.39356
[103]	train-mlogloss:0.41754	eval-mlogloss:0.38998
[104]	train-mlogloss:0.41483	eval-mlogloss:0.38741
[105]	train-mlogloss:0.41137	eval-mlogloss:0.38366
[106]	train-mlogloss:0.40870	eval-mlogloss:0.38085
[107]	train-mlogloss:0.40627	eval-mlogloss:0.37863
[108]	train-mlogloss:0.40276	eval-mlogloss:0.37466
[109]	train-mlogloss:0.40014	eval-mlogloss:0.37210
[110]	train-mlogloss:0.39700	eval-mlogloss:0.36867
[111]	train-mlogloss:0.39387	eval-mlogloss:0.36523
[112]	train-mlogloss:0.39117	eval-mlogloss:0.36233
[113]	train-mlogloss:0.38847	eval-mlogloss:0.35958
[114]	train-mlogloss:0.38539	eval-mlogloss:0.35626
[115]	train-mlogloss:0.38231	eval-mlogloss:0.35301
[116]	train-mlogloss:0.37935	eval-mlogloss:0.34977
[117]	train-mlogloss:0.37629	eval-mlogloss:0.34668
[118]	train-mlogloss:0.37343	eval-mlogloss:0.34367
[119]	train-mlogloss:0.37069	eval-mlogloss:0.34070
[120]	train-mlogloss:0.36777	eval-mlogloss:0.33765
[121]	train-mlogloss:0.36506	eval-mlogloss:0.33471
[122]	train-mlogloss:0.36231	eval-mlogloss:0.33170
[123]	train-mlogloss:0.35969	eval-mlogloss:0.32881
[124]	train-mlogloss:0.35736	eval-mlogloss:0.32616
[125]	train-mlogloss:0.35465	eval-mlogloss:0.32317
[126]	train-mlogloss:0.35197	eval-mlogloss:0.32024
[127]	train-mlogloss:0.34936	eval-mlogloss:0.31752
[128]	train-mlogloss:0.34772	eval-mlogloss:0.31598
[129]	train-mlogloss:0.34515	eval-mlogloss:0.31321
[130]	train-mlogloss:0.34313	eval-mlogloss:0.31127
[131]	train-mlogloss:0.34162	eval-mlogloss:0.30974
[132]	train-mlogloss:0.33934	eval-mlogloss:0.30733
[133]	train-mlogloss:0.33715	eval-mlogloss:0.30513
[134]	train-mlogloss:0.33461	eval-mlogloss:0.30220
[135]	train-mlogloss:0.33224	eval-mlogloss:0.29970
[136]	train-mlogloss:0.32989	eval-mlogloss:0.29714
[137]	train-mlogloss:0.32744	eval-mlogloss:0.29433
[138]	train-mlogloss:0.32509	eval-mlogloss:0.29171
[139]	train-mlogloss:0.32274	eval-mlogloss:0.28927
[140]	train-mlogloss:0.32065	eval-mlogloss:0.28703
[141]	train-mlogloss:0.31882	eval-mlogloss:0.28529
[142]	train-mlogloss:0.31701	eval-mlogloss:0.28339
[143]	train-mlogloss:0.31524	eval-mlogloss:0.28172
[144]	train-mlogloss:0.31339	eval-mlogloss:0.27972
[145]	train-mlogloss:0.31127	eval-mlogloss:0.27740
[146]	train-mlogloss:0.30956	eval-mlogloss:0.27578
[147]	train-mlogloss:0.30743	eval-mlogloss:0.27352
[148]	train-mlogloss:0.30534	eval-mlogloss:0.27118
[149]	train-mlogloss:0.30330	eval-mlogloss:0.26901
[150]	train-mlogloss:0.30121	eval-mlogloss:0.26660
[151]	train-mlogloss:0.29959	eval-mlogloss:0.26490
[152]	train-mlogloss:0.29782	eval-mlogloss:0.26291
[153]	train-mlogloss:0.29582	eval-mlogloss:0.26077
[154]	train-mlogloss:0.29404	eval-mlogloss:0.25922
[155]	train-mlogloss:0.29208	eval-mlogloss:0.25698
[156]	train-mlogloss:0.29020	eval-mlogloss:0.25499
[157]	train-mlogloss:0.28812	eval-mlogloss:0.25274
[158]	train-mlogloss:0.28645	eval-mlogloss:0.25107
[159]	train-mlogloss:0.28461	eval-mlogloss:0.24918
[160]	train-mlogloss:0.28271	eval-mlogloss:0.24711
[161]	train-mlogloss:0.28086	eval-mlogloss:0.24505
[162]	train-mlogloss:0.27897	eval-mlogloss:0.24283
[163]	train-mlogloss:0.27753	eval-mlogloss:0.24132
[164]	train-mlogloss:0.27613	eval-mlogloss:0.23987
[165]	train-mlogloss:0.27438	eval-mlogloss:0.23803
[166]	train-mlogloss:0.27300	eval-mlogloss:0.23657
[167]	train-mlogloss:0.27188	eval-mlogloss:0.23538
[168]	train-mlogloss:0.27042	eval-mlogloss:0.23383
[169]	train-mlogloss:0.26872	eval-mlogloss:0.23193
[170]	train-mlogloss:0.26706	eval-mlogloss:0.23000
[171]	train-mlogloss:0.26574	eval-mlogloss:0.22869
[172]	train-mlogloss:0.26409	eval-mlogloss:0.22692
[173]	train-mlogloss:0.26278	eval-mlogloss:0.22551
[174]	train-mlogloss:0.26148	eval-mlogloss:0.22417
[175]	train-mlogloss:0.26025	eval-mlogloss:0.22290
[176]	train-mlogloss:0.25862	eval-mlogloss:0.22119
[177]	train-mlogloss:0.25713	eval-mlogloss:0.21953
[178]	train-mlogloss:0.25553	eval-mlogloss:0.21771
[179]	train-mlogloss:0.25405	eval-mlogloss:0.21604
[180]	train-mlogloss:0.25251	eval-mlogloss:0.21437
[181]	train-mlogloss:0.25098	eval-mlogloss:0.21268
[182]	train-mlogloss:0.24987	eval-mlogloss:0.21152
[183]	train-mlogloss:0.24891	eval-mlogloss:0.21049
[184]	train-mlogloss:0.24781	eval-mlogloss:0.20926
[185]	train-mlogloss:0.24636	eval-mlogloss:0.20761
[186]	train-mlogloss:0.24511	eval-mlogloss:0.20610
[187]	train-mlogloss:0.24358	eval-mlogloss:0.20433
[188]	train-mlogloss:0.24218	eval-mlogloss:0.20272
[189]	train-mlogloss:0.24131	eval-mlogloss:0.20190
[190]	train-mlogloss:0.24010	eval-mlogloss:0.20062
[191]	train-mlogloss:0.23857	eval-mlogloss:0.19920
[192]	train-mlogloss:0.23727	eval-mlogloss:0.19776
[193]	train-mlogloss:0.23614	eval-mlogloss:0.19657
[194]	train-mlogloss:0.23517	eval-mlogloss:0.19569
[195]	train-mlogloss:0.23377	eval-mlogloss:0.19412
[196]	train-mlogloss:0.23249	eval-mlogloss:0.19274
[197]	train-mlogloss:0.23120	eval-mlogloss:0.19126
[198]	train-mlogloss:0.23014	eval-mlogloss:0.19010
[199]	train-mlogloss:0.22888	eval-mlogloss:0.18879
[200]	train-mlogloss:0.22766	eval-mlogloss:0.18741
[201]	train-mlogloss:0.22641	eval-mlogloss:0.18608
[202]	train-mlogloss:0.22518	eval-mlogloss:0.18471
[203]	train-mlogloss:0.22394	eval-mlogloss:0.18336
[204]	train-mlogloss:0.22269	eval-mlogloss:0.18191
[205]	train-mlogloss:0.22162	eval-mlogloss:0.18076
[206]	train-mlogloss:0.22048	eval-mlogloss:0.17954
[207]	train-mlogloss:0.21935	eval-mlogloss:0.17848
[208]	train-mlogloss:0.21843	eval-mlogloss:0.17767
[209]	train-mlogloss:0.21732	eval-mlogloss:0.17657
[210]	train-mlogloss:0.21621	eval-mlogloss:0.17534
[211]	train-mlogloss:0.21516	eval-mlogloss:0.17422
[212]	train-mlogloss:0.21402	eval-mlogloss:0.17298
[213]	train-mlogloss:0.21292	eval-mlogloss:0.17179
[214]	train-mlogloss:0.21186	eval-mlogloss:0.17063
[215]	train-mlogloss:0.21074	eval-mlogloss:0.16930
[216]	train-mlogloss:0.20963	eval-mlogloss:0.16813
[217]	train-mlogloss:0.20856	eval-mlogloss:0.16693
[218]	train-mlogloss:0.20753	eval-mlogloss:0.16583
[219]	train-mlogloss:0.20638	eval-mlogloss:0.16456
[220]	train-mlogloss:0.20527	eval-mlogloss:0.16329
[221]	train-mlogloss:0.20419	eval-mlogloss:0.16214
[222]	train-mlogloss:0.20312	eval-mlogloss:0.16102
[223]	train-mlogloss:0.20215	eval-mlogloss:0.15995
[224]	train-mlogloss:0.20132	eval-mlogloss:0.15911
[225]	train-mlogloss:0.20056	eval-mlogloss:0.15831
[226]	train-mlogloss:0.19980	eval-mlogloss:0.15738
[227]	train-mlogloss:0.19880	eval-mlogloss:0.15625
[228]	train-mlogloss:0.19791	eval-mlogloss:0.15537
[229]	train-mlogloss:0.19738	eval-mlogloss:0.15485
[230]	train-mlogloss:0.19670	eval-mlogloss:0.15417
[231]	train-mlogloss:0.19568	eval-mlogloss:0.15337
[232]	train-mlogloss:0.19475	eval-mlogloss:0.15230
[233]	train-mlogloss:0.19378	eval-mlogloss:0.15110
[234]	train-mlogloss:0.19287	eval-mlogloss:0.15014
[235]	train-mlogloss:0.19204	eval-mlogloss:0.14937
[236]	train-mlogloss:0.19143	eval-mlogloss:0.14870
[237]	train-mlogloss:0.19052	eval-mlogloss:0.14769
[238]	train-mlogloss:0.18979	eval-mlogloss:0.14702
[239]	train-mlogloss:0.18912	eval-mlogloss:0.14624
[240]	train-mlogloss:0.18848	eval-mlogloss:0.14561
[241]	train-mlogloss:0.18770	eval-mlogloss:0.14495
[242]	train-mlogloss:0.18693	eval-mlogloss:0.14400
[243]	train-mlogloss:0.18622	eval-mlogloss:0.14329
[244]	train-mlogloss:0.18557	eval-mlogloss:0.14268
[245]	train-mlogloss:0.18471	eval-mlogloss:0.14172
[246]	train-mlogloss:0.18389	eval-mlogloss:0.14079
[247]	train-mlogloss:0.18312	eval-mlogloss:0.13998
[248]	train-mlogloss:0.18230	eval-mlogloss:0.13910
[249]	train-mlogloss:0.18174	eval-mlogloss:0.13856
[250]	train-mlogloss:0.18111	eval-mlogloss:0.13786
[251]	train-mlogloss:0.18029	eval-mlogloss:0.13686
[252]	train-mlogloss:0.17957	eval-mlogloss:0.13607
[253]	train-mlogloss:0.17895	eval-mlogloss:0.13524
[254]	train-mlogloss:0.17854	eval-mlogloss:0.13477
[255]	train-mlogloss:0.17775	eval-mlogloss:0.13389
[256]	train-mlogloss:0.17696	eval-mlogloss:0.13302
[257]	train-mlogloss:0.17640	eval-mlogloss:0.13245
[258]	train-mlogloss:0.17575	eval-mlogloss:0.13172
[259]	train-mlogloss:0.17500	eval-mlogloss:0.13084
[260]	train-mlogloss:0.17433	eval-mlogloss:0.13012
[261]	train-mlogloss:0.17364	eval-mlogloss:0.12946
[262]	train-mlogloss:0.17307	eval-mlogloss:0.12899
[263]	train-mlogloss:0.17240	eval-mlogloss:0.12820
[264]	train-mlogloss:0.17167	eval-mlogloss:0.12754
[265]	train-mlogloss:0.17089	eval-mlogloss:0.12665
[266]	train-mlogloss:0.17012	eval-mlogloss:0.12590
[267]	train-mlogloss:0.16963	eval-mlogloss:0.12546
[268]	train-mlogloss:0.16904	eval-mlogloss:0.12470
[269]	train-mlogloss:0.16846	eval-mlogloss:0.12407
[270]	train-mlogloss:0.16798	eval-mlogloss:0.12357
[271]	train-mlogloss:0.16737	eval-mlogloss:0.12289
[272]	train-mlogloss:0.16690	eval-mlogloss:0.12257
[273]	train-mlogloss:0.16647	eval-mlogloss:0.12213
[274]	train-mlogloss:0.16598	eval-mlogloss:0.12155
[275]	train-mlogloss:0.16542	eval-mlogloss:0.12090
[276]	train-mlogloss:0.16479	eval-mlogloss:0.12019
[277]	train-mlogloss:0.16417	eval-mlogloss:0.11946
[278]	train-mlogloss:0.16371	eval-mlogloss:0.11902
[279]	train-mlogloss:0.16323	eval-mlogloss:0.11853
[280]	train-mlogloss:0.16292	eval-mlogloss:0.11820
[281]	train-mlogloss:0.16238	eval-mlogloss:0.11779
[282]	train-mlogloss:0.16190	eval-mlogloss:0.11721
[283]	train-mlogloss:0.16145	eval-mlogloss:0.11673
[284]	train-mlogloss:0.16097	eval-mlogloss:0.11622
[285]	train-mlogloss:0.16041	eval-mlogloss:0.11559
[286]	train-mlogloss:0.15993	eval-mlogloss:0.11504
[287]	train-mlogloss:0.15936	eval-mlogloss:0.11447
[288]	train-mlogloss:0.15883	eval-mlogloss:0.11396
[289]	train-mlogloss:0.15835	eval-mlogloss:0.11361
[290]	train-mlogloss:0.15779	eval-mlogloss:0.11295
[291]	train-mlogloss:0.15739	eval-mlogloss:0.11262
[292]	train-mlogloss:0.15678	eval-mlogloss:0.11206
[293]	train-mlogloss:0.15629	eval-mlogloss:0.11147
[294]	train-mlogloss:0.15580	eval-mlogloss:0.11095
[295]	train-mlogloss:0.15546	eval-mlogloss:0.11045
[296]	train-mlogloss:0.15496	eval-mlogloss:0.10983
[297]	train-mlogloss:0.15449	eval-mlogloss:0.10923
[298]	train-mlogloss:0.15405	eval-mlogloss:0.10894
[299]	train-mlogloss:0.15359	eval-mlogloss:0.10834

[I 2026-10-22 06:05:17,237] Trial 5 finished with value: 1.0 and parameters: {'lambda': 1.1812648693965519e-07, 'alpha': 0.716487029218384, 'eta': 0.01081935972872932, 'gamma': 1.5525011319703366e-08, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.7998173953066419, 'colsample_bytree': 0.62512153212331}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.90611	eval-mlogloss:0.89815

[I 2026-10-22 06:05:17,287] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.91882	eval-mlogloss:0.91041

[I 2026-10-22 06:05:17,367] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99542	eval-mlogloss:0.98969

[I 2026-10-22 06:05:17,403] Trial 8 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89892	eval-mlogloss:0.89945

[I 2026-10-22 06:05:17,441] Trial 9 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88372	eval-mlogloss:0.87880

[I 2026-10-22 06:05:17,485] Trial 10 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85837	eval-mlogloss:0.84580

[I 2026-10-22 06:05:17,569] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.98754	eval-mlogloss:0.97765

[I 2026-10-22 06:05:17,671] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87912	eval-mlogloss:0.86177

[I 2026-10-22 06:05:17,726] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06517	eval-mlogloss:1.06521
[1]	train-mlogloss:1.03206	eval-mlogloss:1.03101
[2]	train-mlogloss:1.01561	eval-mlogloss:1.01640
[3]	train-mlogloss:1.00031	eval-mlogloss:1.00062

[I 2026-10-22 06:05:17,777] Trial 14 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.03038	eval-mlogloss:1.02799

[I 2026-10-22 06:05:18,237] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.83880	eval-mlogloss:0.82958

[I 2026-10-22 06:05:18,273] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88501	eval-mlogloss:0.87727

[I 2026-10-22 06:05:18,337] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87852	eval-mlogloss:0.87310

[I 2026-10-22 06:05:18,372] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89674	eval-mlogloss:0.88822

[I 2026-10-22 06:05:18,401] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.00804	eval-mlogloss:1.00365

[I 2026-10-22 06:05:18,433] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05236	eval-mlogloss:1.05063
[1]	train-mlogloss:1.00861	eval-mlogloss:1.00457
[2]	train-mlogloss:0.98927	eval-mlogloss:0.98858
[3]	train-mlogloss:0.97000	eval-mlogloss:0.97021

[I 2026-10-22 06:05:18,483] Trial 21 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.91974	eval-mlogloss:0.91244

[I 2026-10-22 06:05:18,515] Trial 22 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.79301	eval-mlogloss:0.76896

[I 2026-10-22 06:05:18,546] Trial 23 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88981	eval-mlogloss:0.89267

[I 2026-10-22 06:05:18,578] Trial 24 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.86529	eval-mlogloss:0.84988

[I 2026-10-22 06:05:18,620] Trial 25 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.79577	eval-mlogloss:0.77287

[I 2026-10-22 06:05:18,688] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88894	eval-mlogloss:0.87759

[I 2026-10-22 06:05:18,735] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.96386	eval-mlogloss:0.95257

[I 2026-10-22 06:05:19,003] Trial 28 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.86604	eval-mlogloss:0.84969

[I 2026-10-22 06:05:19,058] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.76856	eval-mlogloss:0.74305

[I 2026-10-22 06:05:19,091] Trial 30 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.95080	eval-mlogloss:0.94676

[I 2026-10-22 06:05:19,120] Trial 31 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05781	eval-mlogloss:1.05870
[1]	train-mlogloss:1.01871	eval-mlogloss:1.01787
[2]	train-mlogloss:0.99871	eval-mlogloss:1.00226
[3]	train-mlogloss:0.97966	eval-mlogloss:0.98446

[I 2026-10-22 06:05:19,255] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08677	eval-mlogloss:1.08810
[1]	train-mlogloss:1.07254	eval-mlogloss:1.07302
[2]	train-mlogloss:1.05881	eval-mlogloss:1.05832
[3]	train-mlogloss:1.04679	eval-mlogloss:1.04622
[4]	train-mlogloss:1.03342	eval-mlogloss:1.03237
[5]	train-mlogloss:1.02138	eval-mlogloss:1.02028
[6]	train-mlogloss:1.00973	eval-mlogloss:1.00911
[7]	train-mlogloss:1.00028	eval-mlogloss:1.00002
[8]	train-mlogloss:0.98890	eval-mlogloss:0.98834
[9]	train-mlogloss:0.97663	eval-mlogloss:0.97544
[10]	train-mlogloss:0.96463	eval-mlogloss:0.96258
[11]	train-mlogloss:0.95303	eval-mlogloss:0.95007
[12]	train-mlogloss:0.94348	eval-mlogloss:0.94019
[13]	train-mlogloss:0.93417	eval-mlogloss:0.93044
[14]	train-mlogloss:0.92264	eval-mlogloss:0.91840
[15]	train-mlogloss:0.91152	eval-mlogloss:0.90672

[I 2026-10-22 06:05:19,452] Trial 33 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.05298	eval-mlogloss:1.05345
[1]	train-mlogloss:1.00152	eval-mlogloss:0.99900
[2]	train-mlogloss:0.95479	eval-mlogloss:0.94852
[3]	train-mlogloss:0.91397	eval-mlogloss:0.90645

[I 2026-10-22 06:05:19,513] Trial 34 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08522	eval-mlogloss:1.08649
[1]	train-mlogloss:1.06913	eval-mlogloss:1.06943
[2]	train-mlogloss:1.05363	eval-mlogloss:1.05283
[3]	train-mlogloss:1.03993	eval-mlogloss:1.03910

[I 2026-10-22 06:05:19,550] Trial 35 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.91695	eval-mlogloss:0.90905

[I 2026-10-22 06:05:19,583] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08422	eval-mlogloss:1.08536
[1]	train-mlogloss:1.07021	eval-mlogloss:1.07056
[2]	train-mlogloss:1.05646	eval-mlogloss:1.05596
[3]	train-mlogloss:1.04326	eval-mlogloss:1.04248

[I 2026-10-22 06:05:20,305] Trial 37 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.04292	eval-mlogloss:1.04208

[I 2026-10-22 06:05:20,767] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07619	eval-mlogloss:1.07823
[1]	train-mlogloss:1.05037	eval-mlogloss:1.05060
[2]	train-mlogloss:1.02589	eval-mlogloss:1.02443
[3]	train-mlogloss:1.00414	eval-mlogloss:1.00229

[I 2026-10-22 06:05:20,824] Trial 39 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.07715	eval-mlogloss:1.07912
[1]	train-mlogloss:1.05220	eval-mlogloss:1.05283
[2]	train-mlogloss:1.02858	eval-mlogloss:1.02761
[3]	train-mlogloss:1.00781	eval-mlogloss:1.00676

[I 2026-10-22 06:05:20,920] Trial 40 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.05543	eval-mlogloss:1.05442
[1]	train-mlogloss:1.01456	eval-mlogloss:1.01137
[2]	train-mlogloss:0.97588	eval-mlogloss:0.97029
[3]	train-mlogloss:0.94025	eval-mlogloss:0.93397

[I 2026-10-22 06:05:21,002] Trial 41 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.07495	eval-mlogloss:1.07723
[1]	train-mlogloss:1.04784	eval-mlogloss:1.04892
[2]	train-mlogloss:1.02246	eval-mlogloss:1.02211
[3]	train-mlogloss:0.99948	eval-mlogloss:0.99848

[I 2026-10-22 06:05:21,080] Trial 42 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.06827	eval-mlogloss:1.07047
[1]	train-mlogloss:1.03420	eval-mlogloss:1.03468
[2]	train-mlogloss:1.00255	eval-mlogloss:1.00113
[3]	train-mlogloss:0.97387	eval-mlogloss:0.97156

[I 2026-10-22 06:05:21,144] Trial 43 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08464	eval-mlogloss:1.08570
[1]	train-mlogloss:1.06737	eval-mlogloss:1.06787
[2]	train-mlogloss:1.05006	eval-mlogloss:1.04921
[3]	train-mlogloss:1.03595	eval-mlogloss:1.03418

[I 2026-10-22 06:05:21,182] Trial 44 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.04520	eval-mlogloss:1.04397

[I 2026-10-22 06:05:21,214] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06978	eval-mlogloss:1.07026
[1]	train-mlogloss:1.03557	eval-mlogloss:1.03405
[2]	train-mlogloss:1.00362	eval-mlogloss:0.99980
[3]	train-mlogloss:0.97644	eval-mlogloss:0.97249

[I 2026-10-22 06:05:21,374] Trial 46 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02223	eval-mlogloss:1.01872

[I 2026-10-22 06:05:21,434] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06491	eval-mlogloss:1.06564
[1]	train-mlogloss:1.02502	eval-mlogloss:1.02335
[2]	train-mlogloss:0.98785	eval-mlogloss:0.98333
[3]	train-mlogloss:0.95634	eval-mlogloss:0.95183

[I 2026-10-22 06:05:21,495] Trial 48 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.06775	eval-mlogloss:1.07009
[1]	train-mlogloss:1.03420	eval-mlogloss:1.03438
[2]	train-mlogloss:1.00243	eval-mlogloss:1.00219
[3]	train-mlogloss:0.97330	eval-mlogloss:0.97450

[I 2026-10-22 06:05:21,550] Trial 49 pruned. Trial was pruned at iteration 4.

--------------------------------------------------------
Best trial: {'lambda': 7.03696704899017e-08, 'alpha': 0.8729637882394724, 'eta': 0.2546503079459186, 'gamma': 0.07877455511076698, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.7007462482960004, 'colsample_bytree': 0.4784077962774125}
Best accuracy: 1.0

In [108]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()