# Handling Date and Time Variable
Handling date and time variables involves `converting raw text into proper timestamp formats and extracting useful parts like day, month, year, or time elapsed`

---
**Main Steps to Handle Date and Time** 
* `Convert Data Type:` Change string or object columns into formal datetime objects using tools like Pandas to_datetime so you can run calculations.
* `Extract Features:` Pull hidden details from a single date column, such as the hour, day of the week, month, year, or whether a day is a weekend.
* `Calculate Differences:` Subtract an start time from an end time to find the duration or time delta between two events.
* `Manage Time Zones:` Set or convert all timestamps to a single unified time zone to avoid errors in your data.

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

## Working with Date

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [10]:
# Extract year
date['year'] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [11]:
# Extract month
date['month'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  year  month
33  2019-07-11        3121       17       1  2019      7
574 2019-11-13        5639       25       4  2019     11
808 2019-03-04         995       25       1  2019      3
530 2018-08-22        6007       27       1  2018      8
71  2019-03-30        2918       26       3  2019      3

In [13]:
# Extract month name
date['month_name'] = date['date'].dt.month_name()
date.sample(5)

          date  product_id  city_id  orders  year  month month_name
700 2019-10-23        2669       25      20  2019     10    October
978 2018-11-13        2845       23       2  2018     11   November
71  2019-03-30        2918       26       3  2019      3      March
417 2018-12-16        1361       20       1  2018     12   December
34  2019-04-09        4185       18      12  2019      4      April

In [14]:
# Extract days
date['days'] = date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  year  month month_name  days
487 2019-04-18        6095        9       1  2019      4      April    18
171 2019-01-25        4964        1      55  2019      1    January    25
885 2019-07-03        7368       25       1  2019      7       July     3
81  2019-03-22        3143       25       1  2019      3      March    22
76  2019-04-18        5973       16       1  2019      4      April    18

In [15]:
# Extract days name
date['day_name'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,days,day_name
290,2018-12-05,4254,16,37,2018,12,December,5,Wednesday
307,2018-12-06,3034,0,1,2018,12,December,6,Thursday
882,2019-10-14,5666,25,2,2019,10,October,14,Monday
747,2018-08-06,2490,7,9,2018,8,August,6,Monday
154,2018-10-10,803,23,2,2018,10,October,10,Wednesday

In [17]:
# Day of the week
date['day_of_the_week'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,days,day_name,day_of_the_week
775,2019-05-27,5968,13,11,2019,5,May,27,Monday,0
228,2019-05-15,6683,13,8,2019,5,May,15,Wednesday,2
74,2019-11-13,2199,14,2,2019,11,November,13,Wednesday,2
568,2019-12-01,4505,25,1,2019,12,December,1,Sunday,6
981,2019-06-17,7526,14,12,2019,6,June,17,Monday,0

In [25]:
date['is_weekend'] = np.where(date['day_name'].isin(['Sunday','Saturday']), 1, 0)
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,days,day_name,day_of_the_week,is_weekend
182,2019-05-26,1135,28,1,2019,5,May,26,Sunday,6,1
41,2019-04-07,2898,18,45,2019,4,April,7,Sunday,6,1
365,2018-07-18,6248,4,2,2018,7,July,18,Wednesday,2,0
435,2018-10-20,4847,26,9,2018,10,October,20,Saturday,5,1
850,2018-12-28,383,25,15,2018,12,December,28,Friday,4,0

In [28]:
# Extract week of the year
date['week_of_the_year'] = date['date'].dt.isocalendar().week
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,days,day_name,day_of_the_week,is_weekend,week,week_of_the_year
690,2018-12-16,3799,20,3,2018,12,December,16,Sunday,6,1,50,50
758,2019-01-03,2306,14,2,2019,1,January,3,Thursday,3,0,1,1
487,2019-04-18,6095,9,1,2019,4,April,18,Thursday,3,0,16,16
550,2019-07-05,5115,2,121,2019,7,July,5,Friday,4,0,27,27
131,2019-04-16,7296,22,11,2019,4,April,16,Tuesday,1,0,16,16

In [30]:
# Extract quarter
date['quarter'] = date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,days,day_name,day_of_the_week,is_weekend,week,week_of_the_year,quarter
35,2019-01-20,2963,22,2,2019,1,January,20,Sunday,6,1,3,3,1
99,2019-04-13,6206,2,24,2019,4,April,13,Saturday,5,1,15,15,2
443,2018-09-21,873,25,16,2018,9,September,21,Friday,4,0,38,38,3
349,2018-09-02,5819,25,4,2018,9,September,2,Sunday,6,1,35,35,3
742,2018-07-15,3627,13,21,2018,7,July,15,Sunday,6,1,28,28,3

In [31]:
# Extract semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.sample(5)

,date,product_id,city_id,orders,year,month,month_name,days,day_name,day_of_the_week,is_weekend,week,week_of_the_year,quarter,semester
922,2019-03-28,1658,16,27,2019,3,March,28,Thursday,3,0,13,13,1,1
571,2018-09-18,5421,9,1,2018,9,September,18,Tuesday,1,0,38,38,3,2
197,2018-09-14,3440,26,101,2018,9,September,14,Friday,4,0,37,37,3,2
976,2019-04-18,5320,13,1,2019,4,April,18,Thursday,3,0,16,16,2,1
375,2019-07-14,2002,1,3,2019,7,July,14,Sunday,6,1,28,28,3,2

In [33]:
# Extract time elasped between dates
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 8, 25, 11, 2, 12, 164743)

In [34]:
today - date['date']

0     2450 days 11:02:12.164743
1     2932 days 11:02:12.164743
2     2863 days 11:02:12.164743
3     2565 days 11:02:12.164743
4     2788 days 11:02:12.164743
                 ...
995   2878 days 11:02:12.164743
996   2819 days 11:02:12.164743
997   2667 days 11:02:12.164743
998   2732 days 11:02:12.164743
999   2506 days 11:02:12.164743
Name: date, Length: 1000, dtype: timedelta64[ns]

In [37]:
(today - date['date']).dt.days

0      2450
1      2932
2      2863
3      2565
4      2788
       ...
995    2878
996    2819
997    2667
998    2732
999    2506
Name: date, Length: 1000, dtype: int64

In [43]:
# Months passed
np.round((today - date['date']) / np.timedelta64(1,'D')/ 30.4375,1)

0      80.5
1      96.3
2      94.1
3      84.3
4      91.6
       ...
995    94.6
996    92.6
997    87.6
998    89.8
999    82.3
Name: date, Length: 1000, dtype: float64

## Working with Time

In [44]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [45]:
time['date'] = pd.to_datetime(time['date'])

In [46]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [49]:
time['hours'] = time['date'].dt.hour
time['minutes'] = time['date'].dt.minute
time['seconds'] = time['date'].dt.second
time.sample(5)

,date,msg,hours,minutes,seconds
399,2015-01-30 23:52:00,парень ищет не скромную девушку 063 410 6482,23,52,0
325,2013-11-20 23:40:00,у+нас+нету+мужиков?! дашка. поставте+даше. кро...,23,40,0
852,2015-12-06 23:40:00,Ищу ВЕРУЮЩУЮ девушку с Днепра. Мне 26. 0987385224,23,40,0
562,2014-09-23 22:45:00,п39 позн с худенк дев067 560 24 93,22,45,0
393,2013-07-06 23:37:00,уеду куда угодно где мой мужчина?,23,37,0

In [51]:
# Extract time part form the date
time['time'] = time['date'].dt.time
time.head()

,date,msg,hours,minutes,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [53]:
# Time difference
today - time['date']

0     4636 days 10:12:12.164743
1     4500 days 11:22:12.164743
2     4986 days 10:41:12.164743
3     4288 days 10:31:12.164743
4     4685 days 11:51:12.164743
                 ...
995   5275 days 10:12:12.164743
996   4596 days 11:48:12.164743
997   5061 days 11:25:12.164743
998   5177 days 11:28:12.164743
999   4449 days 11:37:12.164743
Name: date, Length: 1000, dtype: timedelta64[ns]

In [56]:
(today - time['date']) / np.timedelta64(1, 'h')

0      111274.203379
1      108011.370046
2      119674.686712
3      102922.520046
4      112451.853379
           ...
995    126610.203379
996    110315.803379
997    121475.420046
998    124259.470046
999    106787.620046
Name: date, Length: 1000, dtype: float64

In [57]:
(today - time['date']) / np.timedelta64(1, 'm')

0      6.676452e+06
1      6.480682e+06
2      7.180481e+06
3      6.175351e+06
4      6.747111e+06
           ...
995    7.596612e+06
996    6.618948e+06
997    7.288525e+06
998    7.455568e+06
999    6.407257e+06
Name: date, Length: 1000, dtype: float64

In [58]:
(today - time['date']) / np.timedelta64(1, 's')

0      4.005871e+08
1      3.888409e+08
2      4.308289e+08
3      3.705211e+08
4      4.048267e+08
           ...
995    4.557967e+08
996    3.971369e+08
997    4.373115e+08
998    4.473341e+08
999    3.844354e+08
Name: date, Length: 1000, dtype: float64