# Handling Mixed Variable
**Handling mixed variables in machine learning** requires strategic feature engineering or specialized algorithms because models cannot inherently process combinations of letters, symbols, and numbers within the same input space. Mixed variables usually present themselves in two main ways: **alphanumeric strings combined in a single cell (e.g., ticket codes like "A105") or columns containing entirely numeric values in some rows and categorical values in others.**  

---
## 🛠️ Feature Engineering Strategies
The most common approach is to split the mixed variable into distinct numerical and categorical columns before feeding them into your modeling pipeline  

1. **Splitting Alphanumeric Strings (Regex Extraction)**: When text and numbers are merged together, use regular expressions (regex) to extract the latent components into separate, clean features
   * Text/Category extraction: Extract letters to identify categories like "Deck Level" or "Region".
   * Numerical extraction: Extract digits to represent continuous values like "Room Number" or "ID sequence"
2.  **Segregating Conditional Rows**: If a column contains pure numbers in some rows and string categories in others, use conditional masks to separate them, filling the alternate entries with structural missing placeholders (NaN or 'Unknown')
---

## 🧪 Downstream Encoding & Preprocessing
Once the mixed variable is split into standalone columns, you must apply standard preprocessing techniques to ensure compatibility with your model:
* For the Numerical Component: Handle missing values with median/mean imputation, then scale the values using techniques like `StandardScaler` or `MinMaxScaler`
* For the Categorical Component: Impute missing categories with a string placeholder like `'Missing'` or `'Unknown'`. Transform them using **One-Hot Encoding** for low-cardinality features or **Target Encoding** if the column has high cardinality
---

### Spliting Alphanumerical Strings (Regex Extraction)

In [77]:
import pandas as pd

df = pd.DataFrame({'Cabin': ['C85', 'E36', 'A10', 'C123']})

# Extract categorical letters and numerical digits into separate features
df['Cabin_letter'] = df['Cabin'].str.extract(r'([A-Za-z]+)')
df['Cabin_number'] = df['Cabin'].str.extract(r'(\d+)').astype(float)

In [78]:
df

  Cabin Cabin_letter  Cabin_number
0   C85            C          85.0
1   E36            E          36.0
2   A10            A          10.0
3  C123            C         123.0

### Segregating Conditional Rows

In [79]:
import numpy as np

df = pd.DataFrame({'Ticket': ['113803', 'A/5 21171', 'STON/O2. 3101282', '248706']})

# Isolate numeric values; non-numeric entries become NaN
df['Ticket_numeric'] = pd.to_numeric(df['Ticket'], errors='coerce')

# Isolate string values; pure numeric entries become NaN or a placeholder
df['Ticket_categorical'] = np.where(df['Ticket_numeric'].isnull(), df['Ticket'], np.nan)

In [80]:
df

             Ticket  Ticket_numeric Ticket_categorical
0            113803        113803.0                NaN
1         A/5 21171             NaN          A/5 21171
2  STON/O2. 3101282             NaN   STON/O2. 3101282
3            248706        248706.0                NaN

In [81]:
df = pd.read_csv('titanic.csv')
df.head()

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [82]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [83]:
df['Cabin_numeric'] = df['Cabin'].str.extract(r'(\d+)')
df['Cabin_categorical'] = df['Cabin'].str.extract(r'([A-Za-z]+)')

In [84]:
df

    Cabin            Ticket number  Survived Cabin_numeric Cabin_categorical
0     NaN         A/5 21171      5         0           NaN               NaN
1     C85          PC 17599      3         1            85                 C
2     NaN  STON/O2. 3101282      6         1           NaN               NaN
3    C123            113803      3         1           123                 C
4     NaN            373450      A         0           NaN               NaN
..    ...               ...    ...       ...           ...               ...
886   NaN            211536      3         0           NaN               NaN
887   B42            112053      3         1            42                 B
888   NaN        W./C. 6607      1         0           NaN               NaN
889  C148            111369      2         1           148                 C
890   NaN            370376      3         0           NaN               NaN

[891 rows x 6 columns]

In [85]:
df

    Cabin            Ticket number  Survived Cabin_numeric Cabin_categorical
0     NaN         A/5 21171      5         0           NaN               NaN
1     C85          PC 17599      3         1            85                 C
2     NaN  STON/O2. 3101282      6         1           NaN               NaN
3    C123            113803      3         1           123                 C
4     NaN            373450      A         0           NaN               NaN
..    ...               ...    ...       ...           ...               ...
886   NaN            211536      3         0           NaN               NaN
887   B42            112053      3         1            42                 B
888   NaN        W./C. 6607      1         0           NaN               NaN
889  C148            111369      2         1           148                 C
890   NaN            370376      3         0           NaN               NaN

[891 rows x 6 columns]

In [86]:
df['Ticket_numeric'] = df['Ticket'].apply(lambda s: s.split()[-1])
df['Ticket_numeric'] = pd.to_numeric(df['Ticket_numeric'],errors='coerce')

# extract the first part of ticket as category
df['Ticket_categorical'] = df['Ticket'].apply(lambda s: s.split()[0])
df['Ticket_categorical'] = np.where(df['Ticket_categorical'].str.isdigit(), np.nan, df['Ticket_categorical'])

In [87]:
df

,Cabin,Ticket,number,Survived,Cabin_numeric,Cabin_categorical,Ticket_numeric,Ticket_categorical
0,NaN,A/5 21171,5,0,NaN,NaN,21171.0,A/5
1,C85,PC 17599,3,1,85,C,17599.0,PC
2,NaN,STON/O2. 3101282,6,1,NaN,NaN,3101282.0,STON/O2.
3,C123,113803,3,1,123,C,113803.0,NaN
4,NaN,373450,A,0,NaN,NaN,373450.0,NaN
...,...,...,...,...,...,...,...,...
886,NaN,211536,3,0,NaN,NaN,211536.0,NaN
887,B42,112053,3,1,42,B,112053.0,NaN
888,NaN,W./C. 6607,1,0,NaN,NaN,6607.0,W./C.
889,C148,111369,2,1,148,C,111369.0,NaN
890,NaN,370376,3,0,NaN,NaN,370376.0,NaN

In [90]:
df['Number_numeric'] = pd.to_numeric(df['number'], errors='coerce')
df['Number_categorical'] = np.where(df['Number_numeric'].isnull(), df['number'], np.nan)

In [91]:
df

,Cabin,Ticket,number,Survived,Cabin_numeric,Cabin_categorical,Ticket_numeric,Ticket_categorical,Number_numeric,Number_categorical
0,NaN,A/5 21171,5,0,NaN,NaN,21171.0,A/5,5.0,NaN
1,C85,PC 17599,3,1,85,C,17599.0,PC,3.0,NaN
2,NaN,STON/O2. 3101282,6,1,NaN,NaN,3101282.0,STON/O2.,6.0,NaN
3,C123,113803,3,1,123,C,113803.0,NaN,3.0,NaN
4,NaN,373450,A,0,NaN,NaN,373450.0,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...
886,NaN,211536,3,0,NaN,NaN,211536.0,NaN,3.0,NaN
887,B42,112053,3,1,42,B,112053.0,NaN,3.0,NaN
888,NaN,W./C. 6607,1,0,NaN,NaN,6607.0,W./C.,1.0,NaN
889,C148,111369,2,1,148,C,111369.0,NaN,2.0,NaN
890,NaN,370376,3,0,NaN,NaN,370376.0,NaN,3.0,NaN